/* Geo-Detective glossary. Case text links a term with [[key]] or [[key|shown text]].
 * New cases can add entries in their own "glossary" object; those merge with this list.
 * License: CC BY-SA 4.0
 */
(function () {
  const GW = (window.GW = window.GW || {});
  GW.glossary = Object.assign(GW.glossary || {}, {
    'caliper': ['Caliper log', 'Borehole diameter, in inches. Readings above the bit size show an enlarged hole, where pad tools such as density and neutron read incorrectly.'],
    'neutron': ['Neutron porosity log', 'Hydrogen content of the formation expressed as porosity in limestone units. Water bound in clay raises the reading in shale; gas, with little hydrogen per unit volume, lowers it.'],
    'sonic': ['Sonic log', 'Compressional slowness (DT) in microseconds per foot, the inverse of P-wave velocity. The same velocity controls seismic travel time, so the sonic log is the link between depth in a well and time on seismic. Enlarged hole can cause spikes called cycle skips.'],
    'density-neutron': ['Density–neutron display', 'Bulk density and neutron porosity plotted on compatible scales. In water-bearing clean limestone the curves overlie. Shale separates them one way; gas separates them the other way, called crossover.'],
    'multiple': ['Multiple', 'Energy that has reflected more than once before reaching the receivers. A surface multiple of a strong reflection arrives at about twice its time, with reversed polarity and twice its dip, and can cross primary reflections.'],
    'diffraction': ['Diffraction', 'Energy scattered from a sharp edge such as a fault termination or a bed pinch-out. Migration collapses diffractions; residual energy after imperfect migration appears as short arcs.'],
    'statics': ['Residual statics', 'Small time shifts between traces left after correcting for near-surface velocity and elevation changes. They make reflections look wavy or broken at short wavelengths.'],
    'attenuation': ['Attenuation (Q)', 'Loss of high frequencies as the wavelet travels through rock. Lower Q means stronger loss, so deeper reflections have a lower dominant frequency and coarser resolution.'],
    'phase': ['Wavelet phase', 'The shape of the wavelet independent of its frequency content. A zero-phase wavelet centers its peak on the reflecting boundary; a rotated phase shifts where the peak, trough and zero crossing fall relative to the boundary.'],
    'depth-conversion': ['Depth conversion', 'Transforming a section recorded in two-way time into depth using a velocity model. The velocity model is smoother than the real rock and carries error, so converted depths differ from well depths by amounts that grow with depth.'],
    'footprint': ['Acquisition footprint', 'Amplitude striping that repeats with the spacing of sources and receivers, left over from uneven acquisition geometry.'],
    'pushdown': ['Velocity pull-up and push-down', 'Reflections beneath a body faster than its surroundings arrive earlier and appear raised (pull-up); beneath a slower body they arrive later and appear lowered (push-down). The effect is strongest in time and remains after depth conversion wherever the velocity model is smoother than the rocks.'],
    'two-way-time': ['Two-way time (TWT)', 'Time for seismic energy to travel down to a reflector and back up. Time and depth are not proportional, because velocity changes with depth and laterally.'],
    'reflection': ['Reflection', 'Energy returned to the surface where acoustic impedance changes across a boundary. A continuous reflection usually follows a bedding surface, although it can also follow an unconformity or a fluid contact.'],
    'wavelet': ['Wavelet', 'The short, band-limited signal that the seismic method sends into the ground and records back. Each reflection on a section is a copy of the wavelet scaled by the reflection coefficient, so beds thinner than about a quarter of a wavelength are not separated.'],
    'dominant-frequency': ['Dominant frequency', 'The frequency carrying the most energy in the wavelet. Lower dominant frequency means a longer wavelength and coarser vertical resolution.'],
    'impedance': ['Acoustic impedance', 'P-wave velocity multiplied by bulk density. Reflections come from contrasts in impedance, not from lithology directly, so two different rock types can produce the same reflection.'],
    'noise': ['Seismic noise', 'Recorded energy that is not primary reflection signal: random noise, multiples, residual migration artifacts. Noise lowers the confidence with which a reflection can be followed across the section.'],
    'dimming': ['Amplitude dimming', 'A zone where reflections are weaker than their surroundings. It can come from gas or fluids in the overburden absorbing and scattering energy, from complex structure that the processing did not image well, or from a real change in rock properties.'],
    'normal-fault': ['Normal fault', 'A dip-slip fault in which the hanging wall has moved down relative to the footwall. Normal faults form where the crust is being extended. A well drilled through a normal fault usually has a section of strata missing.'],
    'reverse-fault': ['Reverse fault', 'A dip-slip fault in which the hanging wall has moved up relative to the footwall. Reverse faults form under horizontal shortening. A well drilled through a reverse fault usually penetrates part of the section twice.'],
    'strike-slip': ['Strike-slip fault', 'A fault with mostly horizontal motion parallel to the fault strike. On a single 2D line, horizontal motion of dipping or thickness-varying beds can show vertical offset of reflections, called apparent separation.'],
    'apparent-separation': ['Apparent separation', 'The offset of a marker as it appears in one cross section. It depends on the orientation of the section relative to the slip direction, so it can differ from the true slip in both amount and sense.'],
    'hanging-wall': ['Hanging wall', 'The block above an inclined fault plane.'],
    'footwall': ['Footwall', 'The block below an inclined fault plane.'],
    'throw': ['Throw', 'The vertical component of displacement of a marker across a fault.'],
    'missing-section': ['Missing section', 'An interval of strata present in nearby wells but absent in a given well. A normal fault cut by the borehole, an unconformity, or depositional thinning to zero can each produce one.'],
    'unconformity': ['Unconformity', 'A surface representing a gap in the depositional record, from erosion, non-deposition, or both.'],
    'growth-fault': ['Growth fault', 'A normal fault that moved while sediment was being deposited. Units thicken across the fault into the hanging wall, and offset increases with depth because older units have recorded more of the slip.'],
    'growth-strata': ['Growth strata', 'Sediments deposited while a structure was growing. Their thickness changes across the structure and the change records the timing of deformation.'],
    'rollover': ['Rollover', 'A broad bending of hanging-wall strata down toward a curved (listric) normal fault.'],
    'shale-withdrawal': ['Shale or salt withdrawal', 'Lateral flow of a mobile, low-density layer at depth. Where the mobile layer thins, the overlying strata subside and thicken; where it gathers, they are pushed up.'],
    'wedge': ['Depositional wedge', 'A package of strata that thickens in one direction because more sediment accumulated there, independent of any fault.'],
    'isochore': ['Isochore', 'The vertical thickness of an interval between two picked surfaces, measured at a point.'],
    'anticline': ['Anticline', 'A fold with the oldest rocks in the core and limbs dipping away from the crest.'],
    'drape': ['Drape and differential compaction', 'Sediments deposited over a rigid or less compactible body (a reef, a sand body, a basement high) compact less above that body than beside it, so the overlying layers bend over it after burial even without tectonic shortening.'],
    'buildup': ['Carbonate buildup', 'A mound or reef of carbonate rock built up above the surrounding sea floor by organisms or by carbonate sediment accumulation. Buildups are typically low in gamma ray, high in density and resistivity, and fast in velocity.'],
    'diapir': ['Diapir', 'A body of mobile rock, usually salt or overpressured shale, that has risen and pushed up or pierced the overlying strata.'],
    'incised-valley': ['Incised valley fill', 'A valley cut by rivers when relative sea level fell, later filled as sea level rose again. The base is an erosional surface that truncates the strata below.'],
    'submarine-channel': ['Submarine channel', 'A channel cut and filled by sediment gravity flows on a slope or basin floor. Channels are often stacked and laterally offset as they migrate.'],
    'collapse': ['Collapse feature', 'A sag or depression formed when material below is removed, for example by dissolution of carbonate or evaporite (karst) or by evacuation of mobile sediment. Overlying strata bend down into the space rather than being cut.'],
    'truncation': ['Erosional truncation', 'Reflections that terminate against an overlying surface, showing the strata were cut by erosion.'],
    'onlap': ['Onlap', 'Reflections that terminate against an underlying inclined surface as they are traced toward it.'],
    'gamma-ray': ['Gamma ray log', 'Natural gamma radiation from potassium, thorium and uranium in the rock, in API units. Clay minerals usually carry more of these elements, so higher readings often mean more shale, although potassium feldspar, mica and uranium-rich organic matter also read high.'],
    'resistivity': ['Resistivity log', 'Electrical resistivity of the rock and its pore fluid, in ohm-m, displayed on a logarithmic scale. Hydrocarbons, low porosity and fresh water raise resistivity; saline brine and conductive clays lower it.'],
    'bulk-density': ['Bulk density log', 'Density of the rock including its pore fluid, in g/cm3, from gamma rays scattered back to a pad pressed against the borehole wall. If the hole is enlarged the pad loses contact and the log reads too low.'],
    'washout': ['Washout', 'An enlarged section of borehole, common in weak shale. Pad tools such as the density log read incorrectly across a washout, often much too low.'],
    'calibration': ['Tool calibration', 'The conversion from raw detector counts to physical units. Logs from different vintages, companies or tools can have systematic offsets, so the same unit can read differently from one well to the next.'],
    'depth-uncertainty': ['Depth uncertainty', 'Differences between driller\u2019s depth and logger\u2019s depth, cable stretch, and errors in the lag time of cuttings returning to surface all mean a depth in a well is known only within some metres.'],
    'cuttings-lag': ['Cuttings lag', 'The time taken for rock chips to travel up the annulus to surface. If the lag is estimated incorrectly the sampled lithology is assigned to the wrong depth.'],
    'correlation': ['Well correlation', 'Matching the same stratigraphic surface between wells by the shape and character of the logs. A correlation is a hypothesis: different logs, or different assumptions about faults and thinning, can support different correlations.'],
    'marker': ['Marker bed', 'A thin, laterally persistent unit with a distinctive log response, used as a reference surface in correlation.'],
    'flattening': ['Flattening', 'Displaying logs or seismic with one picked surface made horizontal. It restores that surface to its approximate depositional shape so thickness changes below and above it stand out.'],
    'well-tie': ['Well tie', 'Matching well depths to the seismic section, usually with a velocity model or synthetic seismogram. Errors in the tie shift picks on the section relative to the logs.'],
    'td': ['Total depth (TD)', 'The deepest point reached by the borehole.'],
    'vertical-exaggeration': ['Vertical exaggeration', 'The ratio of vertical to horizontal display scale. Exaggeration makes dips look steeper and folds look tighter than they are.'],
    'calibrated': ['Calibrated uncertainty', 'A confidence distribution is well calibrated when, over many cases, interpretations given 70% weight turn out correct about 70% of the time.'],
    'overlap': ['Distribution overlap', 'The sum, across interpretations, of the smaller of the two weights. It is 100% when two distributions are identical and 0% when they share no weight.'],
    'effective-number': ['Effective number of interpretations', 'One divided by the sum of squared weights. It is 1 when all weight sits on one interpretation and equals the number of interpretations when weight is spread evenly.']
  });
})();
